id: P003247
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W22283
  title: འགོག་སྙོམས་བརྒལ་ལན་གྱི་རྣམ་གཞག
  author: ''
  volumes:
    149b5168886541c7be7bc2c4664852a1:
      image_group_id: I1KG12056
      title: ''
      volume_number: 1
      total_pages: 48
      base_file: v001.txt
