id: I4FDF5DDC
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T02:17:09+00:00'
last_modified: '2022-06-07T18:38:03.712185+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22283
  title: འགོག་སྙོམས་བརྒལ་ལན་གྱི་རྣམ་གཞག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '5868':
      image_group_id: I1KG12056
      title: ''
      total_pages: 48
      order: 1
      base_file: 5868.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
