id: I4FDF5DDC
legacy_id: P003247
ocr_import_info:
  bdrc_scan_id: W22283
  source: bdrc
  ocr_info:
    timestamp: '2020-03-31T02:16:46'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-01T21:21:28.191632+00:00'
last_modified: 2022-09-02 05:21:32.875295
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W22283
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW22283
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: འགོག་སྙོམས་བརྒལ་ལན་གྱི་རྣམ་གཞག
  author: སེ་ར་རྗེ་བཙུན་ཆོས་ཀྱི་རྒྱལ་མཚན།
statistics:
  ocr_word_mean_confidence_index: 0.7249696363076598
  ocr_word_median_confidence_index: 0.7699999809265137
quality: null
bases:
  I1KG12056:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG12056
      total_pages: 48
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG12056.txt
    statistics:
      ocr_word_median_confidence_index: 0.7699999809265137
      ocr_word_mean_confidence_index: 0.7249696363076598
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
